export const categories = [
  "Technology",
  "Design",
  "Business",
  "Lifestyle",
  "Travel",
  "Food & Cooking",
  "Health & Fitness",
  "Education",
  "Entertainment",
  "Sports",
  "Finance",
  "Productivity",
  "Other",
];